### PR TITLE
Add Link(s) to App Store(s)

### PR DESCRIPTION
**Pull request by TPS**
@cgutman If you've anyplace else you've released a binary, feel free to add.  Particularly, I couldn't locate it on F-droid, but if you have or will publish it there, please add that, too.

### CODE REVIEW

**Comment by TPS** [comment]
Ping @cgutman

**Comment by cgutman** [comment]
This isn't actually the source for Android Remote Debugger.

**Comment by TPS** [comment]
Yep, but this is a demo of the library & you link it in the description of the app.  I changed my commit to make that more clear.

**Comment by cgutman** [comment]
I think this change probably belongs in https://github.com/cgutman/AdbLib not here. The app is a demo of the library, not this test harness.

**Comment by TPS** [comment]
Oops.  I'll move it over in a bit. :man_facepalming:

**Comment by TPS** [comment]
@cgutman https://github.com/cgutman/AdbLib/pull/7 puts the GPlay link in the correct repo. 😁

**Pull request closed without merging**
